export default interface AppGlobals{
    hideIntro: boolean;
    chartWidth: string;
    fwIndex: number;
    typeIndex: number;
    colorMode: boolean; showModal: boolean; pieDataMain: { name: string; color: string; value: number; }[][]; names2: string[]; names5: string[]; names7: string[]; names6: string[]; colors2: string[]; colors3: string[]; colors5: string[]; barData: { value: number; }[][]; pieData2: { name: string; color: string; value: number; }[][]; pieJsonObj: {
        id: string; title: string; subtitle: string; type: string; background: string; showlegend: boolean; showtitle: boolean; textsize: string; chartSize: string; ringsize: number; offset: number; strokewidth: string; strokecolor: string; labeltextcolor: string; pointradius: string; strokeopacity: string; verticalbarcolor: string; verticalbaropacity: string; fillopacity: string; showlefttitle: boolean; showbottomtitle: boolean; valuetype: string; divisions: number; tilt: number; labelForEach: boolean; showdescription: boolean; spinnable: boolean; descriptionborder: string; descriptionborderradius: string; linestyling: string; titlecolor: string; subtextcolor: string; descriptioncolor: string; descriptiontextcolor: string; hover: string; introanimation: string; lefttitle: string; bottomtitle: string; showpercentage: boolean; legendposition: string; graphstyling: string; fontfamily: string; labelstyling: string; labelcolorisitemcolor: boolean; description: string; titles: string[]; colors: string[]; names: string[]; data: { name: string; color: string; value: number; }[][];
    }; index: number; pieJsonObj2: {
        id: string; title: string; subtitle: string; type: string; background: string; showlegend: boolean; showtitle: boolean; textsize: string; chartSize: string; ringsize: number; offset: number; strokewidth: string; strokecolor: string; labeltextcolor: string; pointradius: string; strokeopacity: string; verticalbarcolor: string; verticalbaropacity: string; fillopacity: string; showlefttitle: boolean; showbottomtitle: boolean; valuetype: string; divisions: number; tilt: number; labelForEach: boolean; showdescription: boolean; spinnable: boolean; descriptionborder: string; descriptionborderradius: string; linestyling: string; titlecolor: string; subtextcolor: string; descriptioncolor: string; descriptiontextcolor: string; hover: string; introanimation: string; lefttitle: string; bottomtitle: string; showpercentage: boolean; legendposition: string; graphstyling: string; fontfamily: string; labelstyling: string; labelcolorisitemcolor: boolean; description: string; titles: string[]; colors: string[]; names: string[]; data: { name: string; color: string; value: number; }[][];
    }; barComparativeData: { value: number; }[][];
}